---
title: "index"
author: "Amanda Whitmire"
date: "11/30/2017"
output: 
html_document:
code_folding: hide
toc: true
toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## scatterplot

```{r scatterplot}
ggplot(data = mpg, aes(x = displ, y = hwy)) + 
  geom_point()
```

### 'color'

```{r color}
ggplot(data = mpg, aes(x = displ, y = hwy)) + 
  geom_point((aes(color = class)))
```

### 'shape': but need a B&W figure

Changed 'color' to 'shape'

```{r b&w}
ggplot(data = mpg, aes(x = displ, y = hwy)) + 
  geom_point((aes(shape = class)))
```

```{r size}
ggplot(data = mpg, aes(x = cty, y = hwy, size = class, color = fl))+ 
  geom_point(alpha = 0.2)
```

```{r fix color}

ggplot(data = mpg, aes(x = cty, y = hwy, size = class))+ 
  geom_point(alpha = 0.2, color = "blue")
```

## Exercises

```{r ex 5.5.2}

ggplot(data = mpg, aes(x = displ, y = hwy, color = cty))+ 
  geom_point(alpha = 0.4)
```

```{r ex 5.5.4}

ggplot(data = mpg, aes(x = displ, y = hwy, color = displ <5))+ 
  geom_point()
```

## Geoms

```{r geom_examples}

ggplot(mpg, aes(x = drv, y = hwy)) +
  geom_violin()

```

## Multiple geoms

```{r mult_geoms}

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(x=displ, y=hwy)) +
  geom_smooth(aes(x=displ, y=hwy))

```



## Customization

```{r customize}

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Realtionship b/w engine size & MPG",
       x = "Highway MPG",
       y = "Engine Displacement (liters)") +
  theme_bw() +
  theme(text = element_text(size = 16))

```

## Data Wrangling with `dplyr`

```{r}

gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

gapminder

## useful functions to get to know your data:
head(gapminder) # show the first 6 rows of the data
tail(gapminder) #show the last six rows of the data

head(gapminder, 10) #say how many!
tail(gapminder, 9)

## check out the structure of your data
str(gapminder) 

## column headers
names(gapminder) 

## dimensions of the data
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

#combine with c()
c(nrow(gapminder),ncol(gapminder)) #concatenate

## summary statistics
summary(gapminder)

## For everything above, we were operating on the entire `gapminder` dataset.

head(gapminder$lifeExp)
```

`read_csv` is from the `readr` package (part of the tidyverse). It is NOT `read.csv`, which is part of base R. 

## Actually working with `dplyr`

### Filter

```{r filter}

filter(gapminder, lifeExp < 29)

filter(gapminder, country == "Mexico")

swed <- filter(gapminder, country == "Sweden")
life_swed <- mean(swed$lifeExp)

## pipe operator `%>%` 

gapminder %>% head(3)

## let's use the %>% with our Sweden example
gapminder %>% 
  filter(country == "Sweden") %>% 
  summarize(mean_lifeExp = mean(lifeExp))

```

### Select() by columns

```{r select}

## select 2 columns
select(gapminder, year, lifeExp)

## with the pipe operator
gapminder %>%
  select(year, lifeExp) %>%
  tail()

## combine what we've learned

gapminder %>%
  filter(country == "Cambodia") %>%
  select(country, year, pop, gdpPercap)

## same but shorter
gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)  

## a few more things with filter()
gapminder %>%
  filter(country == "Mexico",
         year == 2002)

## `mutate()` to add columns
gapminder %>%
  mutate(gdp = pop * gdpPercap)

#let's add an index
gapminder %>%
  mutate(index = 1:nrow(gapminder)) %>%
  tail()

## combine mutations
gapminder %>%
  mutate(gdp = pop * gdpPercap) %>%
  mutate(index = 1:nrow(gapminder))

## combine mutations
test <- gapminder %>%
  mutate(gdp = pop * gdpPercap, 
         index = 1:nrow(gapminder)) #even shorter!

## not the right way, shouldn't work
gapminder %>%
  filter(country == c("Egypt", "Vietnam"))

## this %in% operator let's you filter multiple things within a `c()`
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam"))

## Exercise: Find the maximum gdpPercap of Egypt and Vietnam -> Create a new column.

gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  mutate(max_gdpPercap = max(gdpPercap))

## group_by() so that we can get two maxes
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  group_by(country) %>%
  # mutate(max_gdpPercap = max(gdpPercap))
  summarize(max_gdpPercap = max(gdpPercap))

gapminder %>%
  group_by(country) %>%
  summarize(max_gdpPercap = max(gdpPercap))

## let's keep the year associated with the max gdp variable
gapminder %>%
  group_by(country) %>%
  mutate(max_gdpPercap = max(gdpPercap)) %>%
  filter(max_gdpPercap == gdpPercap) %>%
  arrange(max_gdpPercap) #if you want descending order, you use arrage(desc(max_gdpPercap))

gapminder %>%
  group_by(country) %>%
  #mutate(max_gdpPercap = max(gdpPercap)) %>%
  filter(gdpPercap == max(gdpPercap)) 

```

# Day 2

## Joining datasets

```{r joining}

## read in the data. (same URL as yesterday, just with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

#create new variable with only gapminder 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007)
gap_2007 %>% head()
gap_2007 %>% str() # 142 rows

# left join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")
lj %>% dim()

# right join gap_2007 to co2
rj <- right_join(gap_2007, co2)
rj %>% dim() # 12 rows
```



